DISPLAY_NAME="gemma-4-E4B-it"
DEST_REPO="gemma-4-E4B-it-GGUF"
DEP_PRIMARY="google/gemma-4-E4B-it"
DEP_ASSISTANT="google/gemma-4-E4B-it-assistant"
DEP_QAT_Q4_0="google/gemma-4-E4B-it-qat-q4_0-unquantized-assistant"
DEP_QAT_Q4_0_UNQUANTIZED="google/gemma-4-E4B-it-qat-q4_0-unquantized"
